version: "3.9"
services:
  db:
    ports:
      - "5433:5432"
    container_name: postgresql_container
    image: postgres:15
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
    restart: unless-stopped
  backend:
    build: .
    container_name: restaurant_image
    ports:
      - "2020:2020"
    environment:
      db-url: jdbc:postgresql://db:5432/restaurant
      db-username: postgres
      db-password: admin123
    depends_on:
      - db
    restart: unless-stopped